name = "ClaudConverterPro"
type = "javascript"
account_id = "54627add21702edb887b738d4fa1b1533b8f0"  # Replace with your actual Account ID
workers_dev = true

[build]
command = "./build.sh"
publish = "public"